---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: nginx-cache
  namespace: monitoring
  labels:
    release: prometheus-operator
spec:
  jobLabel: jobLabel
  namespaceSelector:
    matchNames:
    - {{ $.Release.Namespace }}
  endpoints:
  - path: /metrics
    port: metrics
    honorLabels: true
    relabelConfigs:
    - replacement: nginx-cache
      targetLabel: job
    - source_labels: [__meta_kubernetes_service_name]
      target_label: instance
    - sourceLabels: [__meta_kubernetes_pod_node_name]
      targetLabel: node
    - targetLabel: tier
      replacement: cluster    
  selector:
    matchLabels:
      app: {{ $.Release.Name }}-nginx-cache
