apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ $.Release.Name }}-sysctl
spec:
  selector:
    matchLabels:
      name: sysctl-config
  template:
    metadata:
      labels:
        name: sysctl-config
    spec:
      initContainers:
      - name: sysctl-config
        image: busybox
        securityContext:
          privileged: true  # Required to run sysctl
        command:
        - /bin/sh
        - -c
        - |
          set -o errexit
          set -o xtrace        
          sysctl -w fs.aio-max-nr=524288
          sysctl -w fs.file-max=611160
          sysctl -w kernel.msgmax=131072
          sysctl -w kernel.msgmnb=131072
          sysctl -w kernel.panic=15
          sysctl -w kernel.pid_max=65536
          sysctl -w net.core.optmem_max=16777216
          sysctl -w net.core.somaxconn=65535
          sysctl -w net.ipv4.conf.all.accept_redirects=0
          sysctl -w net.ipv4.conf.all.log_martians=1
          sysctl -w net.ipv4.conf.all.rp_filter=1
          sysctl -w net.ipv4.conf.all.secure_redirects=0
          sysctl -w net.ipv4.conf.all.send_redirects=0
          sysctl -w net.ipv4.conf.default.accept_redirects=0
          sysctl -w net.ipv4.conf.default.accept_source_route=0
          sysctl -w net.ipv4.conf.default.rp_filter=1
          sysctl -w net.ipv4.conf.default.secure_redirects=0
          sysctl -w net.ipv4.conf.default.send_redirects=0
          sysctl -w net.ipv4.ip_forward=0
          sysctl -w net.ipv4.tcp_congestion_control=bbr
          sysctl -w net.ipv4.tcp_fin_timeout=10
          sysctl -w net.ipv4.tcp_keepalive_intvl=10
          sysctl -w net.ipv4.tcp_keepalive_probes=5
          sysctl -w net.ipv4.tcp_keepalive_time=60
          sysctl -w net.ipv4.tcp_max_syn_backlog=65000
          sysctl -w net.ipv4.tcp_max_tw_buckets=1440000
          sysctl -w net.ipv4.tcp_moderate_rcvbuf=1
          sysctl -w net.ipv4.tcp_no_metrics_save=1
          sysctl -w net.ipv4.tcp_notsent_lowat=16384
          sysctl -w net.ipv4.tcp_rfc1337=1
          sysctl -w net.ipv4.tcp_sack=0
          sysctl -w net.ipv4.tcp_slow_start_after_idle=0
          sysctl -w net.ipv4.tcp_synack_retries=2
          sysctl -w net.ipv4.tcp_syncookies=1
          sysctl -w net.ipv4.tcp_syn_retries=2
          sysctl -w net.ipv4.tcp_timestamps=0
          sysctl -w net.ipv4.tcp_tw_reuse=1
          sysctl -w net.ipv4.tcp_window_scaling=0
          sysctl -w net.ipv6.conf.all.disable_ipv6=1
          sysctl -w net.ipv6.conf.default.disable_ipv6=1
          sysctl -w net.ipv6.conf.lo.disable_ipv6=1
          sysctl -w vm.dirty_background_ratio=2
          sysctl -w vm.dirty_ratio=60
          sysctl -w vm.max_map_count=262144
          sysctl -w vm.overcommit_memory=1
          sysctl -w vm.swappiness=1
          sysctl -w net.ipv4.tcp_rmem="4096 87380 16777216"
          sysctl -w net.ipv4.tcp_wmem="4096 65536 16777216"
          sysctl -w net.ipv4.ip_local_port_range="1024 65535"
          sysctl -w kernel.printk="4 4 1 7"

        resources:
          requests:
            cpu: 10m
            memory: 10Mi
        volumeMounts:
        - mountPath: /host-sys
          name: sys
          readOnly: true
      containers:
      - name: pause
        image: k8s.gcr.io/pause:3.9  
        resources:
          requests:
            cpu: 1m
            memory: 1Mi
      hostNetwork: true
      hostPID: true
      restartPolicy: Always
      volumes:
      - name: sys
        hostPath:
          path: /proc/sys
