apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: metallb
  namespace: flux-system
spec:
  interval: 1h
  url: https://metallb.github.io/metallb
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: metallb
  namespace: flux-system
spec:
  interval: 1h
  install:
    createNamespace: true
  targetNamespace: metallb
  chart:
    spec:
      chart: metallb
      sourceRef:
        kind: HelmRepository
        name: metallb
        namespace: flux-system
      interval: 1h
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: metallb-config
  namespace: flux-system
spec:
  interval: 1h
  targetNamespace: metallb
  dependsOn:
    - name: metallb
  chart:
    spec:
      chart: raw
      sourceRef:
        kind: HelmRepository
        name: supu2
        namespace: flux-system
      interval: 1h
  values:
    templates:
    - |
      apiVersion: metallb.io/v1beta1
      kind: IPAddressPool
      metadata:
        name: ip-pool
      spec:
        addresses:
        - {{ .Values.metallb.ipPool}}
    - |
      apiVersion: metallb.io/v1beta1
      kind: L2Advertisement
      metadata:
        name: l2
